const LOCAL_STORAGE_KEYS = {
  MEMBER_ID: 'MEMBER_ID',
  EMAIL: 'EMAIL',
  NICKNAME: 'NICKNAME',
  NEW_MEMBER: 'NEW_MEMBER',
  PROFILE_IMAGE: 'PROFILE_IMAGE',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
};

export default LOCAL_STORAGE_KEYS;
