const LOCAL_STORAGE_KEYS = {
  MEMBER_ID: 'MEMBER_ID',
  EMAIL: 'EMAIL',
  NICKNAME: 'NICKNAME',
  NEW_MEMBER: 'NEW_MEMBER',
  PROFILE_IMAGE: 'PROFILE_IMAGE',
  HAS_MEMBER_INFO: 'HAS_MEMBER_INFO',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REGISTER_STORAGE: 'REGISTER_STORAGE',
};

export default LOCAL_STORAGE_KEYS;
