const ROUTER_PATHS = {
  MAIN: '/',
  MAP: '/map',
  MAP_SEARCH: '/map-search',
  DIRECTIONS: '/directions',
  MY_PAGE: '/my-page',
  LOGIN: '/login',
  SEARCH: '/search',
  LIVE_REVIEW_LIST: '/live-review-list',
  USER_REGISTER: '/user-register',
  PET_REGISTER: '/pet-register',
  PREFERENCE_PLANT: '/preference-plant',
  PREFERENCE_REGION: '/preference-region',
  REGION_NAME: '/region-name',
  PLACE_NAME: '/place-name',
  PENSION_ALL_REVIEW: '/pension-all-review/:id',
  PLACE_ALL_REVIEW: '/place-all-review/:id',
  PET_EDIT_ID: '/pet-edit/:puppyId',
  PET_ADD: '/pet-add',
  USER_EDIT: '/user-edit',
  PLANT_EDIT: '/plant-edit',
  REGION_EDIT: '/region-edit',
  MY_REVIEW: '/my-review',
  MY_REVIEW_EDIT: '/my-review-edit/:id',
  RECENT_VIEW_LIST: '/recent-view-list',
  MEONGSENGNEACUT: '/meongsengneacut',
  SEARCH_MODAL: '/search-modal',
  FACILITY_LIST: '/facility-list',
  PENSION_LIST: '/pension-list',
  PLACE_DETAIL: '/place/:id',
  PENSION_DETAIL: '/pension-detail/:id',
  REVIEW_ADD: '/review-add/:id',
  VIEW_HISTORY: '/view-history',
};

export default ROUTER_PATHS;
