const ROUTER_PATHS = {
  MAIN: '/',
  MAP: '/map',
  MAP_SEARCH: '/map=search',
  DIRECTIONS: '/directions',
  MY_PAGE: '/my-page',
  LOGIN: '/login',
  SEARCH: '/search',
  LIVE_REVIEW: '/live-review',
  USER_REGISTER: '/user-register',
  DOG_REGISTER: '/dog-register',
  PREFERENCE_PLANT: '/preference-plant',
  PREFERENCE_REGION: '/preference-region',
  REGION_NAME: '/region-name',
  PLACE_NAME: '/place-name',
  ALL_REVIEW: '/all-review',
  DOG_UPDATE: '/dog-update',
  DOG_ADD: '/dog-add',
  USER_UPDATE: '/user-update',
  MY_REVIEW: '/my-review',
  MY_REVIEW_MODIFY: '/my-review-modify',
  RECENT_VIEW_LIST: '/recent-view-list',
  RESERVATION: '/reservation',
  RESERVATION_COMPLETE: '/reservation-complete',
  RESERVATION_LIST: '/reservation-list',
  MEONGSENGNEACUT: '/meongsengneacut',
};

export default ROUTER_PATHS;
